format_version: v1.0
type: UniqueComponent
attributes: {id: mcpwm}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: INTR_PWM_FAULT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: mcpwm, value: INT_SOURCE_PWM1}
  - type: Boolean
    attributes: {id: MCPWM_CHANNEL1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: MCPWM_CHANNEL4}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Hex
    attributes: {id: MCPWM_IOCON1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: mcpwm, value: '49152'}
  - type: Hex
    attributes: {id: MCPWM_IOCON2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: mcpwm, value: '49152'}
  - type: Hex
    attributes: {id: MCPWM_IOCON3}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: mcpwm, value: '49152'}
  - type: Hex
    attributes: {id: MCPWM_IOCON4}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: mcpwm, value: '49152'}
  - type: Hex
    attributes: {id: MCPWM_IOCON5}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: mcpwm, value: '49152'}
  - type: Hex
    attributes: {id: MCPWM_IOCON6}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: mcpwm, value: '49152'}
  - type: String
    attributes: {id: PWM_CALLBACK_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: mcpwm, value: MCPWM_CallbackRegister}
  - type: String
    attributes: {id: PWM_GET_PERIOD_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: mcpwm, value: MCPWM_PrimaryPeriodGet}
  - type: String
    attributes: {id: PWM_OUTPUT_DISABLE_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: mcpwm, value: MCPWM_ChannelPinsOwnershipDisable}
  - type: String
    attributes: {id: PWM_OUTPUT_ENABLE_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: mcpwm, value: MCPWM_ChannelPinsOwnershipEnable}
  - type: Hex
    attributes: {id: PWM_PH_MASK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: mcpwm, value: '7'}
  - type: String
    attributes: {id: PWM_PH_U}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: mcpwm, value: MCPWM_CH_1}
  - type: String
    attributes: {id: PWM_PH_V}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: mcpwm, value: MCPWM_CH_2}
  - type: String
    attributes: {id: PWM_PH_W}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: mcpwm, value: MCPWM_CH_3}
  - type: String
    attributes: {id: PWM_SET_DUTY_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: mcpwm, value: MCPWM_ChannelPrimaryDutySet}
  - type: String
    attributes: {id: PWM_START_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: mcpwm, value: MCPWM_Start}
  - type: String
    attributes: {id: PWM_STOP_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: mcpwm, value: MCPWM_Stop}
- type: ElementPosition
  attributes: {x: '520', y: '20', id: mcpwm}
