format_version: v1.0
type: UniqueComponent
attributes: {id: qei2}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: ENCODER_POS_GET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qei2, value: QEI2_PositionGet}
  - type: String
    attributes: {id: ENCODER_POS_SET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qei2, value: QEI2_PositionCountSet}
  - type: String
    attributes: {id: ENCODER_SPEED_GET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qei2, value: QEI2_VelocityGet}
  - type: String
    attributes: {id: ENCODER_SPEED_SET_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qei2, value: QEI2_VelocityCountSet}
  - type: String
    attributes: {id: ENCODER_START_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qei2, value: QEI2_Start}
  - type: String
    attributes: {id: ENCODER_STOP_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qei2, value: QEI2_Stop}
  - type: KeyValueSet
    attributes: {id: QEI2CON__INTDIV}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: KeyValueSet
    attributes: {id: QEI2CON__PIMOD}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Boolean
    attributes: {id: QEI2STAT__IDXIEN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: QEI_EVIC}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qei2, value: '1'}
  - type: Boolean
    attributes: {id: QEI_INDEX_AVAILABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Hex
    attributes: {id: QEI_QEICON}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qei2, value: '1056'}
  - type: Hex
    attributes: {id: QEI_QEISTAT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qei2, value: '1'}
- type: ElementPosition
  attributes: {x: '650', y: '100', id: qei2}
