format_version: v1.0
type: UniqueComponent
attributes: {id: rtcc}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: RTCC_INTERRUPT_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '670', y: '80', id: rtcc}
