format_version: v1.0
type: UniqueComponent
attributes: {id: spi1}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: SPIS_SLAVE_SELECT_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: spi1, value: 'true'}
  - type: Integer
    attributes: {id: SPI_BAUD_RATE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '15000000'}
  - type: Integer
    attributes: {id: SPI_BRG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: spi1, value: '1'}
  - type: Comment
    attributes: {id: SPI_CLOCK_MODE_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '***SPI Mode 3 is Selected***'}
  - type: Boolean
    attributes: {id: SPI_INTERRUPT_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Comment
    attributes: {id: SPI_INTRRUPT_ENABLE_COMMENT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: KeyValueSet
    attributes: {id: SPI_SPICON_CLK_PH}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: KeyValueSet
    attributes: {id: SPI_SPICON_CLK_POL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: KeyValueSet
    attributes: {id: SPI_SPICON_MSSEN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
- type: ElementPosition
  attributes: {x: '366', y: '43', id: spi1}
