format_version: v1.0
type: UniqueComponent
attributes: {id: tmr5}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: TIMER_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr5, value: '60000000'}
  - type: Long
    attributes: {id: TIMER_PERIOD}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr5, value: '17999'}
  - type: Integer
    attributes: {id: TIMER_WIDTH}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr5, value: '16'}
- type: ElementPosition
  attributes: {x: '69', y: '93', id: tmr5}
