format_version: v1.0
type: UniqueComponent
attributes: {id: tmr6}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: TIMER_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr6, value: '60000000'}
  - type: Long
    attributes: {id: TIMER_PERIOD}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr6, value: '29999'}
  - type: Float
    attributes: {id: TIMER_TIME_PERIOD_MS}
    children:
    - type: Attributes
      children:
      - type: Float
        attributes: {id: max}
        children:
        - {type: Value, value: '1092.2833'}
    - type: Values
      children:
      - type: User
        attributes: {value: '500.0'}
  - type: Combo
    attributes: {id: TIMER_UNIT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: microsecon}
  - type: Integer
    attributes: {id: TIMER_WIDTH}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr6, value: '16'}
- type: ElementPosition
  attributes: {x: '81', y: '184', id: tmr6}
