format_version: v1.0
configName: nsensor
folderName: wfi
frameworkPath: C:\Users\nsasp\Harmony3
processor: PIC32MK0512MCJ048
projectName: wfi
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\PIC32MK-MC_DFP\1.11.151\atdf\PIC32MK0512MCJ048.atdf
